### ISSUE TITLE
Innefficient

### ISSUE THREAD

**Issue by Helixable** [1s3k3b/my-first-calculator#1]
I'm sorry, but I looked at index.js and I just had to say something. Can I ask why you went with that method of "Calculation"? No offense :)

**Comment by 1s3k3b** [comment]
haha, the repository is a meme, someone did it in Python a few years ago and I decided to remake it in JS. It's generated, if you look at generator.js you can figure out. I'll find the repository and link it here.

**Comment by 1s3k3b** [comment]
https://github.com/AceLewis/my_first_calculator.py/blob/master/my_first_calculator.py

**Comment by Helixable** [comment]
Oh lol. I was gonna say...
